[theme]
name = "modern"
[theme.overrides]
separator = " "
separator_fg = "#FFFFFF"
separator_bg = "#212121"
idle_bg = "#212121"
info_bg = "#70BCFF"
good_bg = "#67EFB8"
warning_bg = "#FFFF5B"
critical_bg = "#FF5252"

[icons]
name = "awesome"
[icons.overrides]
time = ""

[[block]]
block = "focused_window"

# [[block]]
# block = "weather"
# format = " {weather} {temp}°"
# service = { name = "openweathermap", api_key = "aaa", city_id="aaa", units="metric" }

[[block]]
block = "custom"
command = "echo \"$(echo -e '\uF1EB') $(iwgetid -r)\""
interval = 2

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = " {MFm}/{MTm} MiB"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
upower = true
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 1
format = "%e %B(%m) %Y - %H:%M:%S"
